### ISSUE TITLE
streamlit font

### ISSUE THREAD

**Issue by Mohammadseif** [aghasemi/where2give#1]
hi dr ghasemi.could you help me how can change font size and font style in streamlit for selectbox ??????

**Comment by aghasemi** [comment]
Hi,
I'm no expert in streamlit. Here is what I found by googling: https://discuss.streamlit.io/t/change-font-size-in-st-write/7606
Hope it helps.

**Comment by Mohammadseif** [comment]
Hi,,,I found it by googling too and check streamlit docs but it seems there
isnt no way to fix it..thx 🙏🙏🙏

**Comment by aghasemi** [comment]
You can create an issue in their GitHub repo. They are normally quick to respond and discuss.

**Comment by Mohammadseif** [comment]
Thx for guidance alireza🙏🙏🙏
